# Generated by Django 6.0.2 on 2026-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('unavailable', 'Unavailable'), ('available', 'Available')], default='booked', max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
