# Generated by Django 6.0.2 on 2026-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0002_bookeddate_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
