# Generated by Django 6.0.2 on 2026-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0003_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookeddate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookeddate',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('unavailable', 'Unavailable')], default='booked', max_length=20),
        ),
    ]
