# Generated by Django 6.0.2 on 2026-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0004_alter_bookeddate_date_alter_bookeddate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=200)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.AlterField(
            model_name='bookeddate',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('unavailable', 'Unavailable'), ('available', 'Available')], default='booked', max_length=20),
        ),
    ]
