# Generated by Django 6.0.2 on 2026-03-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
