# Generated by Django 6.0.2 on 2026-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0007_booking_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterModelOptions(
            name='bookeddate',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='bookinginquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookeddate',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=30),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='bookeddate',
            unique_together={('venue', 'date')},
        ),
    ]
