# Generated by Django 6.0.2 on 2026-03-27 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0008_delete_booking_alter_bookeddate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=30)),
                ('date', models.DateField()),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('available', 'Available'), ('unavailable', 'Unavailable'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='available', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_new_date', models.DateField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('venue', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NotesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('admin', models.CharField(default='admin', max_length=100)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_logs', to='testproj.dateentry')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.DeleteModel(
            name='BookedDate',
        ),
        migrations.DeleteModel(
            name='BookingInquiry',
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='testproj.dateentry'),
        ),
    ]
