# Generated by Django 6.0.2 on 2026-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0009_bookinglog_dateentry_noteslog_delete_bookeddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='dateentry',
            old_name='requested_new_date',
            new_name='old_date',
        ),
        migrations.RenameField(
            model_name='noteslog',
            old_name='saved_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='dateentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='noteslog',
            name='admin',
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='email',
            field=models.EmailField(blank=True, help_text='Used by guests to log in to the User Panel', max_length=254, null=True),
        ),
    ]
