# Generated by Django 6.0.2 on 2026-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0010_alter_noteslog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteslog',
            options={},
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
