# Generated by Django 6.0.2 on 2026-03-28 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0011_alter_noteslog_options_alter_dateentry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=30)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
