# Generated by Django 6.0.2 on 2026-03-27 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0011_alter_noteslog_options_alter_dateentry_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=200)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinglog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dateentry',
            options={},
        ),
        migrations.RenameField(
            model_name='noteslog',
            old_name='text',
            new_name='note',
        ),
        migrations.AlterUniqueTogether(
            name='dateentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='noteslog',
            name='entry',
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(default='Initial Log', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('done', 'Done'), ('unavailable', 'Unavailable'), ('rescheduled', 'Rescheduled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noteslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='dateentry',
            name='old_date',
        ),
        migrations.RemoveField(
            model_name='dateentry',
            name='reschedule_reason',
        ),
    ]
