# Generated by Django 6.0.2 on 2026-03-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0012_bookinginquiry'),
        ('testproj', '0012_bookinginquiry_alter_bookinglog_options_and_more'),
    ]

    operations = [
    ]
