# Generated by Django 6.0.2 on 2026-03-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0013_merge_20260328_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglog',
            old_name='timestamp',
            new_name='changed_at',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='action',
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='testproj.dateentry'),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dateentry',
            name='old_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateentry',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('done', 'Done'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=50),
        ),
    ]
