# Generated by Django 6.0.2 on 2026-03-28 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0014_rename_timestamp_bookinglog_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinginquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], default='birthday', max_length=30),
        ),
    ]
