# Generated by Django 6.0.2 on 2026-03-29 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0015_alter_bookinginquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinginquiry',
            options={},
        ),
        migrations.RenameField(
            model_name='bookinglog',
            old_name='changed_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bookinginquiry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bookinglog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dateentry',
            name='old_date',
        ),
        migrations.RemoveField(
            model_name='dateentry',
            name='reschedule_reason',
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinglog',
            name='action',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='venue',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('done', 'Done'), ('unavailable', 'Unavailable'), ('rescheduled', 'Rescheduled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='venue',
            field=models.CharField(choices=[('birthday', 'Birthday & Private Venue'), ('wedding', 'Wedding & Romantic Venue'), ('family', 'Family Milestones Venue'), ('academic', 'Academic & Youth Venue'), ('corporate', 'Corporate & Formal Venue'), ('entertainment', 'Entertainment & Special Venue')], max_length=50),
        ),
    ]
