# Generated by Django 6.0.2 on 2026-03-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproj', '0016_alter_bookinginquiry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dateentry',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookinginquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dateentry',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked'), ('ongoing', 'Ongoing'), ('done', 'Done'), ('unavailable', 'Unavailable'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], default='available', max_length=20),
        ),
    ]
